BlogProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^xadmin/', include('blogAdmin.urls')),
    url(r'', include('comments.urls')),
    # 记得在顶部引入 AllPostsRssFeed
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    # search
    url(r'^search/', include('haystack.urls')),
    # 登录模块
    url(r'^users/', include('django.contrib.auth.urls')),
]
handler404 = 'blog.views.page_not_found'
handler500 = 'blog.views.page_not_found'

blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from blog import views

app_name = 'blog'
SLIG = '\w\d\-\\+\\_\.'

urlpatterns = [
    # 函数（第一个参数是网址，第二个参数是处理函数）
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^records/$', views.ArchiveViewList.as_view(), name="records"),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^post/(?P<slug>[\w\d\-\\+\\_\\.\\:]+)/$', views.detail, name="detail_slug"),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchiveView.as_view(),
        name="archives"),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^category/(?P<slug>[\w\d\-\\+\\_\\.\\:]+)/$', views.CategoryViewByName.as_view(),
        name="category"),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name="tag"),
    url(r'^tag/(?P<slug>[\w\d\-\\+\\_\\.\\:]+)/$', views.TagViewByName.as_view(), name="tag"),
    url(r'^tags/$', views.get_tags_list, name="tag_list"),
    url(r'^test/$', views.findPost, name="findPost"),
    # url(r'^search/$', views.search, name="search"),
]
# ^\\w+

blog/models.py
# coding: utf-8

import markdown
from django.conf import settings

from django.db import models
# 分类
from django.urls import reverse
from django.utils.html import strip_tags


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')
    # 别名
    slug = models.CharField(max_length=150, default="", null=True, verbose_name='分类别名')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_time', 'name']


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=100)
    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')
    # 别名
    slug = models.CharField(max_length=150, default="", null=True, verbose_name='标签别名')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_time', 'name']


class Post(models.Model):
    # 标题
    title = models.CharField(max_length=70, verbose_name='标题')
    # 正文
    body = models.TextField(verbose_name='正文')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified_time = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='修改时间')
    # 摘要
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True, null=True, editable=False,
                               verbose_name='摘要')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
    # 分类的外键
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True,
                                 verbose_name='分类')

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者'
                               , on_delete=models.CASCADE, blank=True, null=True)
    # 内容格式化方式
    fmtType = models.CharField(max_length=20, verbose_name='格式化类型', default='markdown')
    # 阅读量
    views = models.PositiveIntegerField(default=0, editable=False)
    # 别名
    slug = models.CharField(max_length=150, verbose_name='文章别名', null=True, default="")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # 首先实例化一个 Markdown 类，用于渲染 body 的文本
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        # 如果没有摘要
        if not self.excerpt or self.excerpt != strip_tags(md.convert(self.body))[:200]:
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            # self.excerpt = md.convert(self.body)[:200]
            self.excerpt = strip_tags(md.convert(self.body))[:200]
            # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(force_insert, force_update, using,
                               update_fields)

    def get_simple_date(self):
        return self.created_time.strftime("%Y-%m-%d")

    get_simple_date.short_description = u"发布时间"
    short_description = "文章列表"

    class Meta:
        ordering = ['-created_time', 'title']
        verbose_name = '文章'
        verbose_name_plural = '文章'


class BlogSet(models.Model):
    site_name = models.CharField(blank=False, verbose_name='站点名称', max_length=66)
    description = models.TextField(blank=True, verbose_name='站点描述', max_length=150)
    keywords = models.TextField(blank=True, verbose_name='站点关键词', max_length=150)

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = '管理内容'
        verbose_name_plural = '站点管理'


class Friendly(models.Model):
    site_name = models.CharField(blank=False, verbose_name='站点名称', max_length=66)
    link = models.CharField(blank=False, verbose_name='链接', max_length=200)
    sort = models.IntegerField(blank=True, default=0, verbose_name='显示顺序')

    def __str__(self):
        return self.site_name

    class Meta:
        ordering = ['sort', 'site_name']
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'


class Catalog(models.Model):
    index = models.IntegerField(blank=True, default=0, verbose_name='显示顺序')
    name = models.CharField(blank=True, verbose_name='分类名称', max_length=20)
    link = models.CharField(blank=False, verbose_name='分类链接', max_length=20)

    class Meta:
        ordering = ['index']
        verbose_name = '目录'
        verbose_name_plural = '目录'

blog/views.py
# Create your views here.
import markdown
from django.db.models import Q
from django.db.models.aggregates import Count
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic import ListView

from blog.models import Post, Category, Tag
from blogAdmin import utils
from comments.forms import CommentForm


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get("paginator")
        page = context.get("page_obj")
        is_paginated = context.get("is_paginated")
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        # 如果没有分页则返回空
        if not is_paginated:
            return {}
        # 当前页左边连续的页码号，初始值为空
        left = []
        # 当前页右边连续的页码号，初始值为空
        right = []
        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False
        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False
        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False
        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages
        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range
        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 1]
            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            # [-1] 返回数组的最后一个值
            if right[-1] < total_pages - 1:
                right_has_more = True
            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            # 行内if
            left = page_range[(page_number - 2) if (page_number - 2) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 2) if (page_number - 2) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 1]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


#
# class IndexView(ListView):
#     model = Post
#     template_name = 'blog/index.html'
#     context_object_name = 'post_list'
#     paginate_by = 10


def get_tags_list(request):
    tags_list = Tag.objects.annotate(num_posts=Count('post')).order_by("-num_posts")
    return render(request, 'blog/tags.html', context={'tags_list': tags_list})


'''
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get("paginator")
        page = context.get("page_obj")
        is_paginated = context.get("is_paginated")
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}
        # 当前页左边连续的页码号，初始值为空
        left = []
        # 当前页右边连续的页码号，初始值为空
        right = []
        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False
        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False
        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages
        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range
        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]
            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data
'''


def detail(request, slug):
    post = Post.objects.get(slug=slug)
    if post:
        # 阅读量+1
        post.increase_views()
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        # form = CommentForm()
        # 获取评论
        # comment_list = post.comment_set.all()
        # 将表单，文章，评论传递
        context = {'post': post}
        return render(request, 'blog/detail.html', context=context)
    else:
        return render(request, 'blog/detail.html', context={'post': None})


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, args, kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        # 原始body
        # body = '[TOC]\r\n' + post.body
        # # 渲染 Post.body
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',

templates/blog/header.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html class="theme-next gemini use-motion" lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <meta name="theme-color" content="#222">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link href="//cdn.staticfile.org/fancybox/2.1.5/jquery.fancybox.min.css" rel="stylesheet"
          type="text/css">
    <link href="//fonts.googleapis.com/css?family=Monda:300,300italic,400,400italic,700,700italic|Roboto Slab:300,300italic,400,400italic,700,700italic|Lobster Two:300,300italic,400,400italic,700,700italic|Monaco:300,300italic,400,400italic,700,700italic&subset=latin,latin-ext"
          rel="stylesheet" type="text/css">
    <link href="//cdn.staticfile.org/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">
    <link href="{% static 'blog/css/main.css' %}" rel="stylesheet" type="text/css">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'admin/images/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'admin/images/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'admin/images/favicon.ico' %}">
    {% get_blog_set as blogSet %}
    <meta name="keywords" content="{{ keywords }}">
    <meta name="description" content="{{ description }}">
    <meta property="og:type" content="{{ setType }}">
    <meta property="og:title" content="{{ title }}">
    <meta property="og:url" content="{{ url }}">
    <meta property="og:site_name" content="{{ blogSet.site_name }}">
    <meta property="og:description" content="{{ description }}">
    <meta property="og:locale" content="zh-Hans">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{ title }}">
    <meta name="twitter:description" content="{{ description }}">
    <title>{{ title }}</title>
    <script type="text/javascript" id="hexo.configurations">
        var NexT = window.NexT || {};
        var CONFIG = {
            root: '/',
            scheme: 'Gemini',
            sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
            fancybox: true,
            fastclick: true,
            lazyload: true,
            tabs: true,
            motion: {"enable":true,"async":true,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
        };
    </script>
</head>
<div class="container sidebar-position-left {{ type }}">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
        <div class="header-inner">
            <div class="site-brand-wrapper">
                <div class="site-meta">


                    <div class="custom-logo-site-title">
                        <a href="/" class="brand" rel="start">
                            <span class="logo-line-before"><i></i></span>
                            <span class="site-title">{{ blogSet.site_name }}</span>
                            <span class="logo-line-after"><i></i></span>
                        </a>
                    </div>

                    <p class="site-subtitle">{{ blogSet.description }}</p>

                </div>

                <div class="site-nav-toggle">
                    <button>
                        <span class="btn-bar"></span>
                        <span class="btn-bar"></span>
                        <span class="btn-bar"></span>
                    </button>
                </div>
            </div>

            <nav class="site-nav">
                <ul id="menu" class="menu">
                    <li class="menu-item menu-item-home {% is_active request.path '/' %}">
                        <a href="/" rel="section">
                            <i class="menu-item-icon fa fa-fw fa-home"></i> <br/>首页
                        </a>
                    </li>
                    <li class="menu-item menu-item-android {% is_active request.path '/category/Android' %}">
                        <a href="{% url 'blog:category' 'Android' %}" rel="section">
                            <i class="menu-item-icon fa fa-android fa-fw"></i> <br>Android
                        </a>
                    </li>
                    <li class="menu-item menu-item-home {% is_active request.path '/category/sui-yue-ru-ge' %}">
                        <a href="{% url 'blog:category' 'sui-yue-ru-ge' %}" rel="section">
                            <i class="menu-item-icon fa fa-heart fa-fw"></i> <br>岁月如歌
                        </a>
                    </li>
                    <li class="menu-item menu-item-archives {% is_active request.path '/records/' %}">
                        <a href="/records/" rel="section">
                            <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>归档
                        </a>
                    </li>

                    <li class="menu-item menu-item-tags {% is_active request.path '/tags/' %}">
                        <a href="{% url 'blog:tag_list' %}" rel="section">
                            <i class="menu-item-icon fa fa-fw fa-tags"></i> <br>Tags
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main id="main" class="main">
        <div class="main-inner">
            <div class="content-wrap">
                <div id="content" class="content">

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block header %}
    {% get_blog_set as blog %}
    {% url 'blog:index' as blog_url %}
    {% include 'blog/header.html' with keywords=blog.keywords description=blog.description title=blog.site_name url=blog_url setType='website' type='page-homel' %}
{% endblock %}
{% block content %}
    {% get_blog_set as blogSet %}
    <section id="posts" class="posts-expand">
        {% for post in post_list %}
            <article class="post post-type-normal" itemscope="">
                <div class="post-block">
                    <link itemprop="mainEntityOfPage"
                          href="{% url 'blog:detail_slug' slug=post.slug %}"/>
                    <span hidden="" itemprop="author" itemscope="">
      <meta itemprop="name" content="{% get_author %}"/>
      <meta itemprop="description" content="{{ post.body|truncatechars_html:100 }}"/>
      <meta itemprop="image" content="{% avatar_url %}"/> </span>
                    <span hidden="" itemprop="publisher" itemscope="">
      <meta itemprop="name" content="{{ blogSet.site_name }}"/> </span>
                    <header class="post-header">
                        <h1 class="post-title" itemprop="name headline">
                            <a class="post-title-link"
                               href="{% url 'blog:detail_slug' slug=post.slug %}"
                               itemprop="url">{{ post.title }}</a>
                        </h1>
                        <div class="post-meta">
                        <span class="post-time"> <span class="post-meta-item-icon"> <i
                                class="fa fa-calendar-o"></i> </span> <span
                                class="post-meta-item-text">发表于</span> <time title="创建于"
                                                                             itemprop="dateCreated datePublished"
                                                                             datetime="{{ post.created_time }}"> {{ post.created_time|date:"Y-m-d" }} </time> <span
                                class="post-meta-divider">|</span> <span
                                class="post-meta-item-icon"> <i class="fa fa-calendar-check-o"></i> </span> <span
                                class="post-meta-item-text">更新于</span> <time title="更新于"
                                                                             itemprop="dateModified"
                                                                             datetime="{{ post.modified_time }}"> {{ post.modified_time|date:"Y-m-d" }} </time> </span>
                            <span class="post-category"> <span
                                    class="post-meta-divider">|</span> <span
                                    class="post-meta-item-icon"> <i
                                    class="fa fa-folder-o"></i> </span> <span
                                    class="post-meta-item-text">分类于</span> <span itemprop="about"
                                                                                 itemscope="">
                                <a href="{% url "blog:category" post.category.slug %}"
                                   itemprop="url" rel="index"> <span
                                        itemprop="name">{{ post.category.name }}</span> </a> </span> </span>
                            <span class="post-meta-divider">|</span> <span
                                class="post-meta-item-icon"> <i
                                class="fa fa-eye"></i> </span> <span
                                class="post-meta-item-text">阅读次数</span> <span
                                class="leancloud-visitors-count"> {{ post.views }}次</span> </span>
                            <div class="post-wordcount">
                            <span class="post-meta-item-icon"> <i
                                    class="fa fa-file-word-o"></i> </span>
                                <span class="post-meta-item-text">字数统计</span>
                                <span title="字数统计"> {{ post.body|length }} 字 </span>
                                <span class="post-meta-divider">|</span>
                                <span class="post-meta-item-icon"> <i
                                        class="fa fa-tags"></i> </span>
                                <span class="post-meta-item-text">标签</span>
                                <span itemprop="about" itemscope="">
                                      {% for tag in post.tags.all %}
                                          <a href="{% url 'blog:tag' tag.slug %}">{{ tag.name }}</a>
                                          {% if not forloop.last %},{% endif %}
                                      {% endfor %}
                                 </span>
                            </div>
                        </div>
                    </header>
                    <div class="post-body" itemprop="articleBody">
                        {% if post.excerpt %}
                            <p>{{ post.excerpt|safe }}...</p>
                        {% else %}
                            <p>{{ post.body|truncatechars_html:200 }}...</p>
                        {% endif %}
                        <div class="post-button text-center">
                            <a class="btn" href="{% url 'blog:detail_slug' post.slug %}"
                               rel="contents">阅读全文 &raquo; </a>
                        </div>
                    </div>
                    <footer class="post-footer">
                        <div class="post-eof"></div>
                    </footer>
                </div>
            </article>
        {% empty %}
            <div class="no-post">暂时还没有发布的文章！</div>
        {% endfor %}
    </section>
    {% include 'blog/pagination.html' %}
{% endblock %}